enum ROUTES_NAMED {
  MANAGE_EXPENSE = 'MANAGE_EXPENSE',
  RECENT_EXPENSES = 'RECENT_EXPENSES',
  ALL_EXPENSES = 'ALL_EXPENSES',
  EXPENSES_OVERVIEW = 'EXPENSES_OVERVIEW',
  FAVORITE = 'FAVORITE',
}

export default ROUTES_NAMED